#!/usr/bin/env sh

options="Lock\nLogout\nShutdown\nRestart\nSleep\nHibernate"

case "$(echo -e $options | \
     ~/.config/bemenu/bemenu-wrapper --list 10 \
     --prompt 'Select:' )" in
        Shutdown) exec systemctl poweroff;;
        Restart) exec systemctl reboot;;
        Logout) exec sway exit;;
        Suspend) exec systemctl suspend;;
        Hibernate) exec systemctl suspend-then-hibernate;;
        Lock) exec swaylock;;
        #exec systemctl --user start lock.target;;
esac
