idle_bg = "#1e1e2ee5"
idle_fg = "#cdd6f4"
info_bg = "#1e1e2ee5"
info_fg = "#cdd6f4"
good_bg = "#1e1e2ee5"
good_fg = "#cdd6f4"
warning_bg = "#1e1e2ee5"
warning_fg = "#cdd6f4"
critical_bg = "#1e1e2ee5"
critical_fg = "#f38ba8"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
